Fixup docker-compose to run local ocluster-worker.
ocurrent/docker-base-images pull request #226
Opened 2023-04-20 02:18 UTC by tmcgilchrist

Removes the linux/amd64 requirement, we publish arm64 builds of scheduler and worker so this should continue to work on Linux and MacOS (x86 and Arm64).

2023-05-08 03:19 UTC, tmcgilchrist commented
The root Dockerfile is for the deployed service that runs on https://images.ci.ocaml.org, which gets checked by the deployability check. While the other docker file is for running an  ocluster-worker inside a docker container. We need this latter one to build a Docker in Docker image.

I haven't validated this on M1 macs, could you check @benmandrew or @novemberkilo ?

2023-05-10 09:28 UTC, benmandrew commented
The issue I mentioned is fixed in #228; this PR can be merged with the changes detailed above (except for docker-compose.yml line 38).

2023-05-10 23:59 UTC, tmcgilchrist commented
@benmandrew I've left a comment on that line to help with debug. Could you re-test to confirm everything starts up and a linux-arm64 build works?

2023-05-11 10:06 UTC, benmandrew requested changes

2023-05-11 10:06 UTC, benmandrew commented on docker-compose.yml
> +      - --store=rsync:/var/cache/obuilder
It only works if I make the following change:
```suggestion
      - --obuilder-store=rsync:/var/cache/obuilder
```

Is the `--store` argument working for you?

(I am running `git submodule sync --recursive && git submodule update --recursive` to get the right submodules.)

2023-08-07 03:33 UTC, merged